export const employeeListData = [
    {
        firstName: 'Tony',
        lastName: 'Stark',
        street: '10880 Malibu Point',
        city: 'Malibu',
        zipCode: '90265',
        dateOfBirth: '03/29/1970',
        startDate: '08/08/2022',
        state: 'CA',
        department: 'Engineering',
    },
    {
        firstName: 'Steve',
        lastName: 'Rogers',
        street: '569 Leaman Place',
        city: 'Brooklyn Heights',
        zipCode: '11201',
        dateOfBirth: '07/04/1918',
        startDate: '08/11/2022',
        state: 'NY',
        department: 'Marketing',
    },
    {
        firstName: 'Peter',
        lastName: 'Parker',
        street: '20 Ingram Street',
        city: 'Forest Hills',
        zipCode: '11375',
        dateOfBirth: '08/10/1995',
        startDate: '08/10/2022',
        state: 'NY',
        department: 'Sales',
    },
    {
        firstName: 'Tony2',
        lastName: 'Stark',
        street: '10880 Malibu Point',
        city: 'Malibu',
        zipCode: '90265',
        dateOfBirth: '03/29/1970',
        startDate: '08/08/2022',
        state: 'CA',
        department: 'Engineering',
    },
    {
        firstName: 'Steve2',
        lastName: 'Rogers',
        street: '569 Leaman Place',
        city: 'Brooklyn Heights',
        zipCode: '11201',
        dateOfBirth: '07/04/1918',
        startDate: '08/11/2022',
        state: 'NY',
        department: 'Marketing',
    },
    {
        firstName: 'Peter2',
        lastName: 'Parker',
        street: '20 Ingram Street',
        city: 'Forest Hills',
        zipCode: '11375',
        dateOfBirth: '08/10/1995',
        startDate: '08/10/2022',
        state: 'NY',
        department: 'Sales',
    },
    {
        firstName: 'Tony3',
        lastName: 'Stark',
        street: '10880 Malibu Point',
        city: 'Malibu',
        zipCode: '90265',
        dateOfBirth: '03/29/1970',
        startDate: '08/08/2022',
        state: 'CA',
        department: 'Engineering',
    },
    {
        firstName: 'Steve3',
        lastName: 'Rogers',
        street: '569 Leaman Place',
        city: 'Brooklyn Heights',
        zipCode: '11201',
        dateOfBirth: '07/04/1918',
        startDate: '08/11/2022',
        state: 'NY',
        department: 'Marketing',
    },
    {
        firstName: 'Peter3',
        lastName: 'Parker',
        street: '20 Ingram Street',
        city: 'Forest Hills',
        zipCode: '11375',
        dateOfBirth: '08/10/1995',
        startDate: '08/10/2022',
        state: 'NY',
        department: 'Sales',
    },
    {
        firstName: 'Tony4',
        lastName: 'Stark',
        street: '10880 Malibu Point',
        city: 'Malibu',
        zipCode: '90265',
        dateOfBirth: '03/29/1970',
        startDate: '08/08/2022',
        state: 'CA',
        department: 'Engineering',
    },
    {
        firstName: 'Steve4',
        lastName: 'Rogers',
        street: '569 Leaman Place',
        city: 'Brooklyn Heights',
        zipCode: '11201',
        dateOfBirth: '07/04/1918',
        startDate: '08/11/2022',
        state: 'NY',
        department: 'Marketing',
    },
    {
        firstName: 'Peter4',
        lastName: 'Parker',
        street: '20 Ingram Street',
        city: 'Forest Hills',
        zipCode: '11375',
        dateOfBirth: '08/10/1995',
        startDate: '08/10/2022',
        state: 'NY',
        department: 'Sales',
    },

]