//export const employeeListData = [] //For the performance test
export const employeeListData = [
    {
        firstName: 'Tony',
        lastName: 'Stark',
        street: '10880 Malibu Point',
        city: 'Malibu',
        zipCode: '90265',
        dateOfBirth: '03/29/1970',
        startDate: '08/08/2022',
        state: 'CA',
        department: 'Engineering',
    },
    {
        firstName: 'Steve',
        lastName: 'Rogers',
        street: '569 Leaman Place',
        city: 'Brooklyn Heights',
        zipCode: '11201',
        dateOfBirth: '07/04/1918',
        startDate: '08/11/2022',
        state: 'NY',
        department: 'Marketing',
    },
    {
        firstName: 'Peter',
        lastName: 'Parker',
        street: '20 Ingram Street',
        city: 'Forest Hills',
        zipCode: '11375',
        dateOfBirth: '08/10/1995',
        startDate: '08/10/2022',
        state: 'NY',
        department: 'Sales',
    },
    {
        firstName: 'Tonyb',
        lastName: 'Stark',
        street: '10880 Malibu Point',
        city: 'Malibu',
        zipCode: '90265',
        dateOfBirth: '03/29/1970',
        startDate: '08/08/2022',
        state: 'CA',
        department: 'Engineering',
    },
    {
        firstName: 'Steveb',
        lastName: 'Rogers',
        street: '569 Leaman Place',
        city: 'Brooklyn Heights',
        zipCode: '11201',
        dateOfBirth: '07/04/1918',
        startDate: '08/11/2022',
        state: 'NY',
        department: 'Marketing',
    },
    {
        firstName: 'Peterb',
        lastName: 'Parker',
        street: '20 Ingram Street',
        city: 'Forest Hills',
        zipCode: '11375',
        dateOfBirth: '08/10/1995',
        startDate: '08/10/2022',
        state: 'NY',
        department: 'Sales',
    },
    {
        firstName: 'Tonyc',
        lastName: 'Stark',
        street: '10880 Malibu Point',
        city: 'Malibu',
        zipCode: '90265',
        dateOfBirth: '03/29/1970',
        startDate: '08/08/2022',
        state: 'CA',
        department: 'Engineering',
    },
    {
        firstName: 'Stevec',
        lastName: 'Rogers',
        street: '569 Leaman Place',
        city: 'Brooklyn Heights',
        zipCode: '11201',
        dateOfBirth: '07/04/1918',
        startDate: '08/11/2022',
        state: 'NY',
        department: 'Marketing',
    },
    {
        firstName: 'Peterc',
        lastName: 'Parker',
        street: '20 Ingram Street',
        city: 'Forest Hills',
        zipCode: '11375',
        dateOfBirth: '08/10/1995',
        startDate: '08/10/2022',
        state: 'NY',
        department: 'Sales',
    },
    {
        firstName: 'Tonyd',
        lastName: 'Stark',
        street: '10880 Malibu Point',
        city: 'Malibu',
        zipCode: '90265',
        dateOfBirth: '03/29/1970',
        startDate: '08/08/2022',
        state: 'CA',
        department: 'Engineering',
    },
    {
        firstName: 'Steved',
        lastName: 'Rogers',
        street: '569 Leaman Place',
        city: 'Brooklyn Heights',
        zipCode: '11201',
        dateOfBirth: '07/04/1918',
        startDate: '08/11/2022',
        state: 'NY',
        department: 'Marketing',
    },
    {
        firstName: 'Peterd',
        lastName: 'Parker',
        street: '20 Ingram Street',
        city: 'Forest Hills',
        zipCode: '11375',
        dateOfBirth: '08/10/1995',
        startDate: '08/10/2022',
        state: 'NY',
        department: 'Sales',
    },
    {
        firstName: 'Tonye',
        lastName: 'Stark',
        street: '10880 Malibu Point',
        city: 'Malibu',
        zipCode: '90265',
        dateOfBirth: '03/29/1970',
        startDate: '08/08/2022',
        state: 'CA',
        department: 'Engineering',
    },
    {
        firstName: 'Stevee',
        lastName: 'Rogers',
        street: '569 Leaman Place',
        city: 'Brooklyn Heights',
        zipCode: '11201',
        dateOfBirth: '07/04/1918',
        startDate: '08/11/2022',
        state: 'NY',
        department: 'Marketing',
    },
    {
        firstName: 'Petere',
        lastName: 'Parker',
        street: '20 Ingram Street',
        city: 'Forest Hills',
        zipCode: '11375',
        dateOfBirth: '08/10/1995',
        startDate: '08/10/2022',
        state: 'NY',
        department: 'Sales',
    },
    {
        firstName: 'Tonyf',
        lastName: 'Stark',
        street: '10880 Malibu Point',
        city: 'Malibu',
        zipCode: '90265',
        dateOfBirth: '03/29/1970',
        startDate: '08/08/2022',
        state: 'CA',
        department: 'Engineering',
    },
    {
        firstName: 'Stevef',
        lastName: 'Rogers',
        street: '569 Leaman Place',
        city: 'Brooklyn Heights',
        zipCode: '11201',
        dateOfBirth: '07/04/1918',
        startDate: '08/11/2022',
        state: 'NY',
        department: 'Marketing',
    },
    {
        firstName: 'Peterf',
        lastName: 'Parker',
        street: '20 Ingram Street',
        city: 'Forest Hills',
        zipCode: '11375',
        dateOfBirth: '08/10/1995',
        startDate: '08/10/2022',
        state: 'NY',
        department: 'Sales',
    },
    {
        firstName: 'Tonyg',
        lastName: 'Stark',
        street: '10880 Malibu Point',
        city: 'Malibu',
        zipCode: '90265',
        dateOfBirth: '03/29/1970',
        startDate: '08/08/2022',
        state: 'CA',
        department: 'Engineering',
    },
    {
        firstName: 'Steveg',
        lastName: 'Rogers',
        street: '569 Leaman Place',
        city: 'Brooklyn Heights',
        zipCode: '11201',
        dateOfBirth: '07/04/1918',
        startDate: '08/11/2022',
        state: 'NY',
        department: 'Marketing',
    },
    {
        firstName: 'Peterg',
        lastName: 'Parker',
        street: '20 Ingram Street',
        city: 'Forest Hills',
        zipCode: '11375',
        dateOfBirth: '08/10/1995',
        startDate: '08/10/2022',
        state: 'NY',
        department: 'Sales',
    },
    {
        firstName: 'Tonyh',
        lastName: 'Stark',
        street: '10880 Malibu Point',
        city: 'Malibu',
        zipCode: '90265',
        dateOfBirth: '03/29/1970',
        startDate: '08/08/2022',
        state: 'CA',
        department: 'Engineering',
    },
    {
        firstName: 'Steveh',
        lastName: 'Rogers',
        street: '569 Leaman Place',
        city: 'Brooklyn Heights',
        zipCode: '11201',
        dateOfBirth: '07/04/1918',
        startDate: '08/11/2022',
        state: 'NY',
        department: 'Marketing',
    },
    {
        firstName: 'Peterh',
        lastName: 'Parker',
        street: '20 Ingram Street',
        city: 'Forest Hills',
        zipCode: '11375',
        dateOfBirth: '08/10/1995',
        startDate: '08/10/2022',
        state: 'NY',
        department: 'Sales',
    },
    {
        firstName: 'Tonyi',
        lastName: 'Stark',
        street: '10880 Malibu Point',
        city: 'Malibu',
        zipCode: '90265',
        dateOfBirth: '03/29/1970',
        startDate: '08/08/2022',
        state: 'CA',
        department: 'Engineering',
    },
    {
        firstName: 'Stevei',
        lastName: 'Rogers',
        street: '569 Leaman Place',
        city: 'Brooklyn Heights',
        zipCode: '11201',
        dateOfBirth: '07/04/1918',
        startDate: '08/11/2022',
        state: 'NY',
        department: 'Marketing',
    },
    {
        firstName: 'Peteri',
        lastName: 'Parker',
        street: '20 Ingram Street',
        city: 'Forest Hills',
        zipCode: '11375',
        dateOfBirth: '08/10/1995',
        startDate: '08/10/2022',
        state: 'NY',
        department: 'Sales',
    },
]